name: Hourly speakers' corner updates

on:
  schedule:
    - cron: '54 * * * *'

jobs:
  rotate:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install and run
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python host_key_rotation.py
        env:
          ZOOM_API_KEY: ${{ secrets.ZOOM_API_KEY }}
          ZOOM_API_SECRET: ${{ secrets.ZOOM_API_SECRET }}
          HOST_KEY_SALT: ${{ secrets.SC_HOST_KEY_SALT }}
